name: ci

on:
  #   push:
  #     branches:
  #       - '16.0'
  #     paths:
  #       - './odoo/custom/src/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
#       tags:
#         description: 'Test scenario tags'
#         required: false
#         type: boolean
#       environment:
#         description: 'Environment to run tests against'
#         type: environment
#         required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #       -
      #         name: set up git configuration
      #         run: |
      #           git config --global user.email "shellkube@gmail.com"
      #           git config --global user.name "kubeAl"
      #           git config --global user.password ${{ secrets.GIT_TOKEN2 }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . # Specifies the build context (current directory)
          file: ./16.0.Dockerfile # Specifies the path to the Dockerfile relative to the build context
          push: true
          tags: shellkube/kubeERP:16.0-onbuild
          github-token: ${{ secrets.GIT_TOKEN }}
#           ssh-private-key: ${{ secrets.GIT_KUBO16_ACTION_PRIVATE }}
